import tensorflow as tf


class ROIAlignLayer:
    def __init__(self, backbone, pool_size=(7, 7), num_rois=32):
        self.backbone = backbone
        self.pool_size = pool_size
        self.num_rois = num_rois
        self.layer = self.build_layer()

    def roi_align(self, inputs):
        # Separate the inputs
        feature_map = inputs[0]
        rois = inputs[1]

        # Normalize the coordinates of the ROIs by the spatial dimension of the feature map
        rois_norm = rois / tf.cast(tf.shape(feature_map)[1:3], tf.float32)

        # Use crop_and_resize to extract the ROIs and reduce them to the pool size
        rois_aligned = tf.image.crop_and_resize(feature_map, rois_norm, tf.range(tf.shape(rois)[0]), self.pool_size)

        return rois_aligned

    def build_layer(self):
        # Define the input layers
        feature_map_input = self.backbone.model.output
        rois_input = tf.keras.layers.Input(shape=(self.num_rois, 4))

        # Apply the ROIAlign layer
        x = tf.keras.layers.Lambda(self.roi_align)([feature_map_input, rois_input])

        # Create the layer
        layer = tf.keras.Model(inputs=[feature_map_input, rois_input], outputs=x)
        return layer


# TODO:
    
# Key Missing Elements and Considerations

#     ROI Integration:  Currently, your roi_align function doesn't explicitly process the actual region proposals generated by the RPN. You'll need to:
#         Update the function signature to accept the RPN proposals.
#         Ensure the ROI coordinates are in the correct format.

#     Bilinear Interpolation:  The essence of ROI Align is the use of bilinear interpolation to accurately sample features from the feature map, even when ROIs don't perfectly align to the grid. The crop_and_resize function in TensorFlow does allow bilinear interpolation, but you'll need to ensure it's configured correctly within your code.

#     Compatibility with Mask Head: Make sure the output shape of your ROI Align layer is compatible with what your Mask Head expects as input.

# Next Steps

#     Connect RPN Proposals: Modify your code to take the output of your RPN (region proposals) and feed them into the ROI Align layer.
#     Verify Interpolation: Carefully check the crop_and_resize parameters to ensure bilinear interpolation is enabled.
